// Generated by scripts/build-globe-poster.mjs. Do not edit by hand.
// `ratio` is the sprite's width as a share of the page height at the title view.
export const GLOBE_POSTER = {
  ratio: 0.65333,
  src: "/images/globe-poster-1000.webp",
  srcSet: "/images/globe-poster-1000.webp 1000w, /images/globe-poster-1600.webp 1600w",
} as const;
